project:
  type: website
  render:
    - index.qmd
    - chapters/chapter1.qmd

website:
  page-navigation: true
  title: "Supports pédagogiques du module NTICA"
  site-url: "https://ghmercier.github.io/ntica-data"
  repo-url: "https://github.com/ghmercier/ntica-data"
  repo-actions: [ issue ]
  sidebar:
    search: false
    contents:
      - href: index.qmd
        text: Accueil
      - href: chapters/chapter1.qmd
        text: Traitement de tables

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true
  ipynb:
    output: true
