project:
  type: website
  execute-dir: project
  render: # Add HERE new chapters and notebooks
    - index.qmd
    - chapters/outils-quotidiens.qmd
    - chapters/qgis-intro.qmd

website:
  page-navigation: true
  title: "Supports pédagogiques du module NTICA"
  site-url: "https://ghmercier.github.io/ntica-data"
  repo-url: "https://github.com/ghmercier/ntica-data"
  repo-actions: [ issue ]
  sidebar:
    search: false
    contents: # Add HERE new chapters (but not the notebooks)
      - href: index.qmd
        text: Accueil
      - chapters/outils-quotidiens.qmd
      - chapters/qgis-intro.qmd
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: false
  ipynb:
    output: true
