project:
  type: website
  execute-dir: project
  render:
    - index.qmd
    - chapters/outils-quotidiens.qmd
    - chapters/qgis-intro.qmd
    - chapters/donnees-urbanisme.qmd

website:
  page-navigation: true
  title: "Supports pédagogiques du module NTICA"
  site-url: "https://ghmercier.github.io/ntica-data"
  repo-url: "https://github.com/ghmercier/ntica-data"
  repo-actions: [ issue ]
  sidebar:
    search: false
    contents:
      - href: index.qmd
        text: Accueil
      - chapters/outils-quotidiens.qmd
      - chapters/qgis-intro.qmd
      - chapters/donnees-urbanisme.qmd
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: false
  ipynb:
    output: true
