---
title: "Travaux dirigés NTICA"
format: html
author:
  - name: Ghislain Mercier
    url: https://github.com/ghmercier
    email: ghislain.mercier@club-internet.fr
date: "2025-10-17"
---

Bienvenue à vous, chers élèves AMUR de la promo 2025/2026. Vous trouverez
ci-dessous les liens vers les supports pour vous aider à manipuler et 
cartographier des données. 

## Préalable : le SSP Cloud

Certains supports sont interactifs. En cliquant sur le bouton prévu à cet effet
en haut de la page, vous pourrez les lancer dans le Datalab de la plateforme
[SSPCloud](https://datalab.sspcloud.fr/) de l'INSEE. 

Cela présente plusieurs avantages : 

- Vous n'avez ainsi rien à installer
- Vous disposerez de tous les modules requis aux bonnes versions
- Vous aurez accès directement aux données nécessaires 

Il vous faudra préalablement créer un compte gratuitement, en indiquant votre
adresse email `@eleves.enpc.fr`.

## Les supports 

- [Les outils du quotidien](/chapters/outils-quotidiens.html)
- [Introduction à QGIS](/chapters/qgis-intro.html)
- [Traitement de fichiers CSV](/chapters/chapter1.html)
- [TD PLU Bioclimatique](/chapters/plu-bioclimatique.html)
